[package]
name = "AuthorizationService"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.49.0", features = ["full"]}
sqlx = {version = "0.8.6", features = ["runtime-tokio", "postgres", "sqlx-postgres", "chrono", "uuid"]}
axum = {version = "0.8.8", features = ["tokio"]}
chrono = {version = "0.4.44", features = ["serde"]}
serde_json = {version = "1.0.149"}
serde = { version = "1.0.228", features = ["derive"] }
hmac = {version = "0.13.0"}
sha2 = {version = "0.11.0"}
jsonwebtoken = {version = "10.3.0", features = ["rust_crypto"]}
logger = {path = "../logger"}
auth_rpc = {path = "../auth_rpc"}
tonic = {version = "0.14.6", features = ["codegen"]}
argon2 = {version = "0.5.3", features = ["std", "alloc", "password-hash"]}
