services:
  psql:
    image: postgres:18
    command: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aRVt74A29_6f
      POSTGRES_DB: TestDB
    ports:
      - '8000:5432'
    volumes:
      - ../Database/init_database.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend_server:
    build:
      context: ../CommandProjectBackend
      target: start
    env_file:
      - server.env
    ports:
      - '8080:8080'
    depends_on:
      psql:
        condition: service_healthy