services:
  psql:
    image: postgres:18
    command: postgres
    environment:
      POSTGRES_USER: ${DB_SUPERUSER:?}
      POSTGRES_PASSWORD: ${DB_SUPERUSER_PASSWORD:?}
      POSTGRES_DB: ${DB_NAME:?}
      DB_USER: ${DB_USER:?}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:?}
    ports:
      - '8000:5432'
    volumes:
      - ../Database/init_database.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_SUPERUSER:?}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  authorization_service:
    build:
      context: ..
      dockerfile: AuthorizationService/Dockerfile
      target: start
    environment:
      JWT_KEY: ${JWT_KEY:?}
      AUTH_HOST: ${AUTH_HOST:?}
      AUTH_PORT: ${AUTH_PORT:?}
      DB_PORT: ${DB_PORT:?}
      DB_HOST: ${DB_HOST:?}
      DB_NAME: ${DB_NAME:?}
      DB_USER: ${DB_USER:?}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD:?}
    depends_on:
      psql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- -T 3 -t 1 http://$$AUTH_HOST:$$AUTH_PORT/healthcheck | grep -qi 'status.*active'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend_server:
    build:
      context: ..
      dockerfile: CommandProjectBackend/Dockerfile
      target: start
    environment:
      SERVER_HOST: ${SERVER_HOST:?}
      SERVER_PORT: ${SERVER_PORT:?}
    ports:
      - '8080:8080'
    depends_on:
      authorization_service:
        condition: service_healthy
