syntax = "proto3";

package auth;

import "google/protobuf/empty.proto";

service Auth {
  rpc CreateNewUser (UserBody) returns (CreateUserResult);
  rpc AuthUser (UserBody) returns (AuthUserResult);
  rpc Health (google.protobuf.Empty) returns (HealthResult);
}

message UserBody {
  string email = 1;
  string password = 2;
}

message CreateUserResult {
  oneof result {
    string token = 1;
    CreateUserError error = 2;
    ServerError server_error = 3;
  }
}

enum CreateUserError {
  EMAIL_USED = 0;
}

message AuthUserResult {
  oneof result {
    string token = 1;
    AuthUserError error = 2;
    ServerError server_error = 3;
  }
}

enum AuthUserError {
  USER_NOT_FOUND = 0;
}

enum ServerError {
  DB_ERROR = 0;
  INTERNAL_SERVER_ERROR = 1;
}

message TokenResult {
  string token = 1;
}

message HealthResult {
  HealthStatus status = 1;
  optional string message = 2;
}

enum HealthStatus {
  OK = 0;
  WARNING = 1;
  ERROR = 2;
}
