[package]
name = "CommandProjectBackend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.49.0", features = ["full"]}
axum = {version = "0.8.8", features = ["tokio", "macros"]}
chrono = {version = "0.4.44"}
serde_json = {version = "1.0.149"}
serde = { version = "1.0.228", features = ["derive"] }
logger = {path = "../logger"}
auth_rpc = {path = "../auth_rpc"}
reqwest = {version = "0.11.0", features = ["json", "rustls-tls"], default-features = false}
utoipa-swagger-ui = {version = "9.0.2", features = ["axum"]}
utoipa = {version="5.5.0", features = ["axum_extras"]}
tonic = {version = "0.14.6"}


[[bin]]
name = "create_api_docs"
path = "src/create_api.rs"